[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
futures = "0.3.21"
tokio-tungstenite = "0.17"

[dependencies.tokio]
version = "1.17"
features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "time",
]
